LXI H,2501 ;GET ADDRESS OF FIRST NUMBER IN H L PAIR

MOV A,M ;FIRST NUMBER IN ACCUMULATOR
INX H ; CONTENT OF HL PAIR INC FORM 2501 TO 2502
ADD M ;1ST NUM ADD 2ND NUMBER
STA 2503 ; STORE THE ACCUMULATOR CONTENT OF MEMORY LOCATIO 2503H
HLT ;STOP