LXI H,2501 ;GET ADDRESS OF FIRST NUMBER IN H L PAIR
MOV A,M ;FIRST NUMBER IN ACCUMULATOR
INX H ; CONTENT OF HL PAIR INC FORM 2501 TO 2502
SUB M ;1ST NUM MINUS 2ND NUMBER
INX H ;INC THE CONTENT OF HL PAIR
MOV M,A ;STORE RESULT OF ACCUMULATOR AT MEMORY LOCATION 2503H
HLT ;STOP